version: "3"
services:
  www:
    build: .
    container_name: sf-php-www
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html/
    links:
      - db
    networks:
      - default
    depends_on:
      - db
  db:
    image: mysql
    container_name: sf-php-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sistema
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf-php-admin
    links:
      - db:db
    ports:
      - 8002:80
    environment:
      MYSQL_ROOT_PASSWORD: 123
